Controllers/CalendarController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using Newtonsoft.Json;
using SoftservePortalNew.Model_Manager;
using SoftservePortalNew.Models;
using SoftservePortalNew.View_Models.Calendar;
using SoftservePortalNew.Assistant_Classes;

namespace SoftservePortalNew.Controllers
{
    public class CalendarController : Controller
    {
        // GET: Calendar

        public ActionResult SocialCalendar()
        {
            if (Session["clsUser"] != null)
            {
                ViewBag.bIsUserLoggedIn = true;
                ViewBag.bIsClientLoggedIn = false;
            }
            else
            {
                ViewBag.bIsUserLoggedIn = null;
                ViewBag.bIsClientLoggedIn = null;

                return RedirectToAction("Index", "Home");
            }

            clsSocialCalendarEventsTypesManager clsSocialCalendarEventsTypesManager = new clsSocialCalendarEventsTypesManager();
            clsSocialCalendarView clsSocialCalendarView = new clsSocialCalendarView();

            clsSocialCalendarView.lstSocialCalendarEventsTypes = clsSocialCalendarEventsTypesManager.getAllSocialCalendarEventsTypesOnlyList();
            return View(clsSocialCalendarView);
        }
        public ActionResult SocialCalendarView()
        {
            if (Session["clsClient"] != null)
            {
                ViewBag.bIsUserLoggedIn = false;
                ViewBag.bIsClientLoggedIn = true;
            }
            else
            {
                ViewBag.bIsUserLoggedIn = null;
                ViewBag.bIsClientLoggedIn = null;

                return RedirectToAction("Index", "Home");
            }

            clsSocialCalendarEventsManager clsSocialCalendarEventsManager = new clsSocialCalendarEventsManager();
            List<clsSocialCalendarEventsViewItems> lstSocialCalendarEvents = clsSocialCalendarEventsManager.getAllSocialCalendarEventsViewItemsOnlyList();

            return View(lstSocialCalendarEvents);
        }

        public ActionResult GetSocialCalendarEvents()
        {
            if (Session["clsUser"] != null)
            {
                ViewBag.bIsUserLoggedIn = true;
                ViewBag.bIsClientLoggedIn = false;
            }
            else
            {
                ViewBag.bIsUserLoggedIn = null;
                ViewBag.bIsClientLoggedIn = null;

                return RedirectToAction("Index", "Home");
            }

            bool bEventAdded = false;

            try
            {
                clsSocialCalendarEventsManager clsSocialCalendarEventsManager = new clsSocialCalendarEventsManager();
                List<clsSocialCalendarEventsItems> lstSocialCalendarEvents = clsSocialCalendarEventsManager.getAllSocialCalendarEventsItemsOnlyList();

                return Json(new { lstSocialCalendarEvents = lstSocialCalendarEvents }, JsonRequestBehavior.AllowGet);
            }
            catch (Exception ex)
            {
                return Json(new { bEventAdded = bEventAdded }, JsonRequestBehavior.AllowGet);
            }
        }

        public ActionResult GetSocialCalendarViewEvents()
        {
            if (Session["clsClient"] != null)
            {
                ViewBag.bIsUserLoggedIn = false;
                ViewBag.bIsClientLoggedIn = true;
            }
            else
            {
                ViewBag.bIsUserLoggedIn = null;
                ViewBag.bIsClientLoggedIn = null;

                return RedirectToAction("Index", "Home");
            }

            bool bEventAdded = false;

            try
            {
                clsSocialCalendarEventsManager clsSocialCalendarEventsManager = new clsSocialCalendarEventsManager();
                List<clsSocialCalendarEventsViewItems> lstSocialCalendarViewEvents = clsSocialCalendarEventsManager.getAllSocialCalendarEventsViewItemsOnlyList();

                return Json(new { lstSocialCalendarViewEvents = lstSocialCalendarViewEvents }, JsonRequestBehavior.AllowGet);
            }
            catch (Exception ex)
            {
                return Json(new { bEventAdded = bEventAdded }, JsonRequestBehavior.AllowGet);
            }
        }

        public ActionResult GetSocialCalendarEventInfo(string strEventID)
        {
            if (Session["clsUser"] != null)
            {
                ViewBag.bIsUserLoggedIn = true;
                ViewBag.bIsClientLoggedIn = false;
            }
            else
            {
                ViewBag.bIsUserLoggedIn = null;
                ViewBag.bIsClientLoggedIn = null;

                return RedirectToAction("Index", "Home");
            }

            clsSocialCalendarEvents clsSocialCalendarEvent = null;
            bool bEventExists = false;
            int iEventID = 0;

            try
            {
                if (strEventID != null && strEventID != "")
                    iEventID = Convert.ToInt32(strEventID);

                clsSocialCalendarEventsManager clsSocialCalendarEventsManager = new clsSocialCalendarEventsManager();
                clsSocialCalendarEvent = clsSocialCalendarEventsManager.getSocialCalendarEventByID(iEventID);

                if (clsSocialCalendarEvent != null)
                {
                    bEventExists = true;
                    return Json(new { bEventExists = bEventExists, clsSocialCalendarEvent = clsSocialCalendarEvent }, JsonRequestBehavior.AllowGet);
                }
                else
                {
                    return Json(new { bEventExists = bEventExists, clsSocialCalendarEvent = clsSocialCalendarEvent }, JsonRequestBehavior.AllowGet);
                }

            }
            catch (Exception ex)
            {
                return Json(new { bEventExists = bEventExists, clsSocialCalendarEvent = clsSocialCalendarEvent }, JsonRequestBehavior.AllowGet);
            }
        }

        [HttpPost]
        public ActionResult AddSocialCalendarEvent(string strTitle, string strEventStart, string strEventEnd, string strEventType, string strEventDescription, string strEventKeywords, string strEventLinks, string strRepeatEventType)
        {
            if (Session["clsUser"] != null)
            {
                ViewBag.bIsUserLoggedIn = true;
                ViewBag.bIsClientLoggedIn = false;
            }
            else
            {
                ViewBag.bIsUserLoggedIn = null;
                ViewBag.bIsClientLoggedIn = null;

                return RedirectToAction("Index", "Home");
            }

            bool bEventAdded = false;
            bool bEventExists = false;
            bool bIsRepeatEvent = false;
            int iEventID = 0;

            try
            {
                clsSocialCalendarEventsManager clsSocialCalendarEventsManager = new clsSocialCalendarEventsManager();
                clsSocialCalendarEvents clsSocialCalendarEvent = new clsSocialCalendarEvents();

                DateTime dtStartDate = Convert.ToDateTime(strEventStart);
                DateTime dtEndDate = Convert.ToDateTime(strEventEnd);

                int iEventType = 0;
                if (strEventType != null && strEventType != "")
                    iEventType = Convert.ToInt32(strEventType);

                bEventExists = clsSocialCalendarEventsManager.checkIfSocialCalendarEventExists(strTitle, dtStartDate, dtEndDate);

                if (bEventExists == true)
                {
                    return Json(new { bEventAdded = bEventAdded, bEventExists = bEventExists, iEventID = iEventID }, JsonRequestBehavior.AllowGet);
                }
                else
                {
                    clsSocialCalendarEvent.strTitle = strTitle;
                    clsSocialCalendarEvent.dtStartDate = dtStartDate;
                    clsSocialCalendarEvent.dtEndDate = dtEndDate;
                    if (iEventType != 0)
                        clsSocialCalendarEvent.iSocialCalendarEventsTypeID = iEventType;
                    clsSocialCalendarEvent.strDescription = strEventDescription;
                    clsSocialCalendarEvent.strKeywords = strEventKeywords;
                    clsSocialCalendarEvent.strLinks = strEventLinks;
                    if (strRepeatEventType != null && strRepeatEventType != "")
                    {
                        clsSocialCalendarEvent.strTitle = clsSocialCalendarEvent.strTitle + " (Repeat)";
                        iEventID = clsSocialCalendarEventsManager.saveSocialCalendarEvent(clsSocialCalendarEvent);

                        bIsRepeatEvent = true;

                        clsSocialCalendarEvent.iSocialCalendarEventID = iEventID;
                        clsSocialCalendarEvent.bIsRepeatEvent = true;
                        clsSocialCalendarEvent.strRepeatEventType = strRepeatEventType;
                        clsSocialCalendarEvent.iRepeatEventStartDateID = iEventID;
                        clsSocialCalendarEvent.dtRepeatEventStartDate = dtStartDate;
                    }

                    if (iEventID == 0)
                        iEventID = clsSocialCalendarEventsManager.saveSocialCalendarEvent(clsSocialCalendarEvent);

                    int iDifferenceInDays = (dtEndDate - dtStartDate).Days;

                    if (clsSocialCalendarEvent.bIsRepeatEvent == true)
                    {
                        if (clsSocialCalendarEvent.strRepeatEventType.ToUpper() == "DAILY")
                        {
                            if (!(iDifferenceInDays > 1))
                            {
                                DateTime dtReapeatDateTimeDailyStart = dtStartDate;
                                DateTime dtReapeatDateTimeDailyEnd = dtEndDate;

                                int iStartDay = dtStartDate.Day + 1; //Begin Repeat on following day
                                int iDaysInMonth = DateTime.DaysInMonth(dtStartDate.Year, dtStartDate.Month);

                                while (iStartDay <= iDaysInMonth)

Views/Calendar/SocialCalendarView.cshtml
@model IEnumerable<SoftservePortalNew.Assistant_Classes.clsSocialCalendarEventsViewItems>

@{
    ViewBag.Title = "EventCalendarView";
}

<div class="content-header row">
    <div class="content-header-left col-md-6 col-12 mb-2">
        <div class="row breadcrumbs-top">
            <div class="breadcrumb-wrapper col-12">
                <ol class="breadcrumb">
                    <li class="breadcrumb-item">
                        <a href="@Url.Action("Index", "Home")">Home</a>
                    </li>
                    <li class="breadcrumb-item active">
                        Social Calendar Events
                    </li>
                </ol>
            </div>
        </div>
        <h3 class="content-header-title">Social Calendar Events</h3>

    </div>
    @*<div class="content-header-right col-md-6 col-12">
            <fieldset class="form-group relative has-icon-left col-md-5 col-12 float-right p-0">
                <input class="form-control" id="iconLeft" type="text" placeholder="Search...">
                <div class="form-control-position"><i class="fa fa-search"></i></div>
            </fieldset>
        </div>*@
</div>
<div class="content-body">
    <!-- Calendar section start -->
    <section id="clndr-examples">
        <div class="row">
            <!-- Adjacent -->
            <div class="col-xl-6 col-lg-12 col-sm-12">
                <div class="card card-height-600">
                    <div class="card-header">
                        <h4 class="card-title">Social Calendar Events</h4>
                        <a class="heading-elements-toggle"><i class="fa fa-ellipsis font-medium-3"></i></a>
                        <div class="heading-elements">
                            <ul class="list-inline mb-0">
                                <li><a data-action="collapse"><i class="ft-minus"></i></a></li>
                                @*<li><a data-action="reload"><i class="ft-rotate-cw"></i></a></li>*@
                                <li><a data-action="expand"><i class="ft-maximize"></i></a></li>
                                @*<li><a data-action="close"><i class="ft-x"></i></a></li>*@
                            </ul>
                        </div>
                    </div>
                    <div class="card-body">
                        <p class="card-text">
                            Events
                        </p>
                        <div id="SocialClndr" class="overflow-hidden bg-grey bg-lighten-3"></div>
                    </div>
                </div>
            </div>
        </div>
        <div id="clndr" class="clearfix">
            <script type="text/template" id="clndr-template">
                <div class="clndr-controls">
                    <div class="clndr-previous-button">&lt;</div>
                    <div class="clndr-next-button">&gt;</div>
                    <div class="current-month">
                        <%= month %>
                        <%= year %>
                    </div>
                </div>
                <div class="clndr-grid">
                    <div class="days-of-the-week clearfix">
                        <% _.each(daysOfTheWeek, function(day) { %>
                        <div class="header-day">
                            <%= day %>
                        </div>
                        <% }); %>
                    </div>
                    <div class="days">
                        <% _.each(days, function(day) { %>
                        <div class="<%= day.classes %>" id="<%= day.id %>">
                            <span class="day-number">
                                <%= day.day %>
                            </span>
                        </div>
                        <% }); %>
                    </div>
                </div>
                <div class="event-listing">
                    <div class="event-listing-title">Event this month</div>
                    <div class="event-listing-inner-size-set">
                        <% _.each(eventsThisMonth, function(event) { %>
                        <div class="event-item font-small-3">
                            <div class="event-item-day font-small-2">
                                <%= event.startDate %>
                            </div>
                            <div class="event-item-name text-bold-600">
                                <%= event.title %>
                            </div>
                            <div class="event-item-location">
                                <%= event.location %>
                            </div>
                        </div>
                        <% }); %>
                    </div>
                </div>
            </script>
        </div>
    </section>
    <!-- Calendar section end -->
</div>


@section scripts {

    @Scripts.Render("~/bundles/clndrscripts")

    <script type="text/javascript">

        /****************************************
        *			Adjacent CLNDR			*
        ****************************************/

        $('#SocialClndr').clndr({
            template: $('#clndr-template').html(),
            showAdjacentMonths: true,
            adjacentDaysChangeMonth: true,
            forceSixRows: true
        });

    </script>

<script type="text/javascript">

    function jsGetSocialCalendarEventsViewItems() {
        //Clear Event Info Items
        $.ajax({
            url: '@Url.Action("GetSocialCalendarViewEvents", "Calendar")',
            type: "GET",
            success: function (data) {
                // states is your JSON array
                var list = data.lstSocialCalendarViewEvents;
                var socialCalendar = $('#SocialClndr').clndr();
                socialCalendar.setEvents(data.lstSocialCalendarViewEvents);
            }
        });
    }

    window.onload = function () {
        jsGetSocialCalendarEventsViewItems();
    }

</script>
}