Controllers/AnalyticsController.cs
using Google.Apis.AnalyticsReporting.v4;
using Google.Apis.Auth.OAuth2;
using Newtonsoft.Json;
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Threading.Tasks;
using System.Web;
using System.Web.Mvc;
using SoftservePortalNew.Model_Manager;
using SoftservePortalNew.Models;
using SoftservePortalNew.View_Models.Analytics;
using System.Net.Http;
using Google.Apis.Auth;

namespace Softserve_Frontend_Mar_2018.Controllers
{
    public class AnalyticsController : Controller
    {
        // GET: Analytics
        public ActionResult Google()
        {
            if (Session["clsUser"] != null)
            {
                ViewBag.bIsUserLoggedIn = true;
                ViewBag.bIsClientLoggedIn = false;
            }
            else
            {
                ViewBag.bIsUserLoggedIn = null;
                ViewBag.bIsClientLoggedIn = null;

                return RedirectToAction("Index", "Home");
            }

            clsDomainsManager clsDomainsManager = new clsDomainsManager();
            clsGogleAnalytics clsGogleAnalytics = new clsGogleAnalytics();

            clsGogleAnalytics.lstDomains = clsDomainsManager.getAllDomainsWithGoogleAnalyticsList().Where(Domain => Domain.clsClient != null).ToList();

            return View(clsGogleAnalytics);
        }

        public ActionResult Facebook()
        {
            if (Session["clsUser"] != null)
            {
                ViewBag.bIsUserLoggedIn = true;
                ViewBag.bIsClientLoggedIn = false;

            }
            else if (Session["clsClient"] != null)
            {
                ViewBag.bIsUserLoggedIn = false;
                ViewBag.bIsClientLoggedIn = true;
            }
            else
            {
                ViewBag.bIsUserLoggedIn = null;
                ViewBag.bIsClientLoggedIn = null;
            }

            analytics analytics = new analytics();
            using (StreamReader r = new StreamReader(@"C:\Users\SoftservePC1\Documents\SoftserveDigital Repositories\SoftservePortalNew\SoftservePortalNew\Content\app-assets\json\posts.json"))
            {
                string json = r.ReadToEnd();
                analytics.RootObject = JsonConvert.DeserializeObject<RootObject>(json);
            }
            using (StreamReader s = new StreamReader(@"C:\Users\SoftservePC1\Documents\SoftserveDigital Repositories\SoftservePortalNew\SoftservePortalNew\Content\app-assets\json\page-impressions.json"))
            {
                string jsons = s.ReadToEnd();
                analytics.Page_Impressions = JsonConvert.DeserializeObject<Page_Impressions>(jsons);
            }
            return View(analytics);
        }

        public ActionResult _DomainGoogleAnalyticsReportPartial()
        {
            if (Session["clsUser"] != null)
            {
                ViewBag.bIsUserLoggedIn = true;
                ViewBag.bIsClientLoggedIn = false;
            }
            else
            {
                ViewBag.bIsUserLoggedIn = null;
                ViewBag.bIsClientLoggedIn = null;

               return RedirectToAction("Index", "Home");
            }

            return PartialView();
        }

        private static void WriteLine(object result)
        {
            throw new NotImplementedException();
        }

        [HttpPost]
        public ActionResult GetDomainGoogleAnalyticsReport(int iDomainID)
        {
            if (Session["clsUser"] != null)
            {
                ViewBag.bIsUserLoggedIn = true;
                ViewBag.bIsClientLoggedIn = false;
            }
            else
            {
                ViewBag.bIsUserLoggedIn = null;
                ViewBag.bIsClientLoggedIn = null;

                return RedirectToAction("Index", "Home");
            }

            bool bHasTokenAndPropertyID = false;

            clsDomainsManager clsDomainsManager = new clsDomainsManager();
            clsDomains clsDomain = clsDomainsManager.getDomainByID(iDomainID);

            string strGAToken = "";
            string strGAPropertyID = "";

            //string jsonPath = AppDomain.CurrentDomain.BaseDirectory + "\\Content\\app-assets\\json\\AneliticksApi-7acaf0fff6a7.json";
            string jsonPath = AppDomain.CurrentDomain.BaseDirectory + "Content\\app-assets\\json\\portalanalytics-215414-7f01944d6065.json";
            
            string[] scopes = new string[] { AnalyticsReportingService.Scope.AnalyticsReadonly }; // Put your scopes here

            var stream = new FileStream(jsonPath, FileMode.Open, FileAccess.Read);

            try
            {
                Task<string> task = GoogleCredential.FromStream(stream).CreateScoped(scopes).UnderlyingCredential.GetAccessTokenForRequestAsync();
                task.Wait();
                string bearer = task.Result;

                strGAToken = bearer;
            }
            catch (AggregateException ex)
            {
                throw ex.InnerException;
            }

            if (clsDomain != null)
                strGAPropertyID = clsDomain.strGoogleAnalyticsCode;

            TempData["strGAToken"] = strGAToken;
            TempData["strGAPropertyID"] = strGAPropertyID;
            TempData["iDomainID"] = iDomainID;

            bHasTokenAndPropertyID = true;

            return Json(new { bHasTokenAndPropertyID = bHasTokenAndPropertyID }, JsonRequestBehavior.AllowGet);
        }
    }
}

Views/Analytics/Facebook.cshtml
@model SoftservePortalNew.View_Models.Analytics.analytics

<div class="content-header row">
    <div class="content-header-left col-md-6 col-12 mb-2">
        <div class="row breadcrumbs-top">
            <div class="breadcrumb-wrapper col-12">
                <ol class="breadcrumb">
                    <li class="breadcrumb-item">
                        <a href="@Url.Action("Index", "Home")">Home</a>
                    </li>
                    <li class="breadcrumb-item active">
                        Facebook Analytics
                    </li>
                </ol>
            </div>
        </div>
        <h3 class="content-header-title"> Facebook Analytics</h3>

    </div>
    @*<div class="content-header-right col-md-6 col-12">
            <fieldset class="form-group relative has-icon-left col-md-5 col-12 float-right p-0">
                <input class="form-control" id="iconLeft" type="text" placeholder="Search...">
                <div class="form-control-position"><i class="fa fa-search"></i></div>
            </fieldset>
        </div>*@
</div>
<div class="content-body">
    <!-- Google bar charts section start -->
    <section id="google-bar-charts">
        <div class="row">
            <div class="col-12 mt-3 mb-1">
                <h4 class="text-uppercase">Minimal Statistics Cards</h4>
                <p>Statistics on minimal cards.</p>
            </div>
        </div>
        <div class="row">
            <div class="col-xl-3 col-lg-6 col-12">
                <div class="card">
                    <div class="card-content">
                        <div class="card-body">
                            <div class="media d-flex">
                                <div class="media-body text-left">
                                    <h3 class="danger">278</h3>
                                    <span>New Projects</span>
                                </div>
                                <div class="align-self-center">
                                    <i class="icon-rocket danger font-large-2 float-right"></i>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
            <div class="col-xl-3 col-lg-6 col-12">
                <div class="card">
                    <div class="card-content">
                        <div class="card-body">
                            <div class="media d-flex">
                                <div class="media-body text-left">
                                    <h3 class="success">156</h3>
                                    <span>New Clients</span>
                                </div>
                                <div class="align-self-center">
                                    <i class="icon-user success font-large-2 float-right"></i>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>

            <div class="col-xl-3 col-lg-6 col-12">
                <div class="card">
                    <div class="card-content">
                        <div class="card-body">
                            <div class="media d-flex">
                                <div class="media-body text-left">
                                    <h3 class="warning">64.89 %</h3>
                                    <span>Conversion Rate</span>
                                </div>
                                <div class="align-self-center">
                                    <i class="icon-pie-chart warning font-large-2 float-right"></i>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
            <div class="col-xl-3 col-lg-6 col-12">
                <div class="card">
                    <div class="card-content">
                        <div class="card-body">
                            <div class="media d-flex">
                                <div class="media-body text-left">
                                    <h3 class="info">423</h3>
                                    <span>Support Tickets</span>
                                </div>
                                <div class="align-self-center">
                                    <i class="icon-support info font-large-2 float-right"></i>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
        <!-- Bar Chart -->
        <div class="row">
            <!-- Simple Doughnut Chart -->
            <div class="col-md-8 col-sm-12">
                <div class="card">
                    <div class="card-header">
                        <h4 class="card-title">Facebook posts</h4>
                        <a class="heading-elements-toggle"><i class="ft-ellipsis-h font-medium-3"></i></a>
                        <div class="heading-elements">
                            <ul class="list-inline mb-0">
                                <li><a data-action="collapse"><i class="ft-minus"></i></a></li>
                                <li><a data-action="reload"><i class="ft-rotate-cw"></i></a></li>
                                <li><a data-action="expand"><i class="ft-maximize"></i></a></li>
                            </ul>
                        </div>
                    </div>
                    <div class="card-content">
                        <div class="card-body">
                            <div class="media-list media-bordered">
                                <div class="media">
                                    <h4 class="media-head text-uppercase"></h4>
                                </div>
                                @foreach (var item in Model.Pa)
                                {
                                    <div class="media">
                                        <a class="media-left" href="#">
                                            <img class="media-object rounded-circle" src="@item.full_picture" alt="Generic placeholder image" style="width: 64px;height: 64px;">
                                        </a>
                                        <div class="media-body" style="width:">
                                            @item.message
                                        </div>
                                    </div>
                                }
                            </div>
                        </div>
                    </div>
                </div>

            </div>
        </div>
        <!-- Column Chart -->
        <div class="row">

        </div>
    </section>
    <!-- // Google bar charts section end -->
</div>
<script src="~/Content/app-assets/js/scripts/cards/card-statistics.js"></script>

Views/Analytics/Google2.cshtml
@model SoftservePortalNew.View_Models.Analytics.clsGogleAnalytics

@{ 
ViewBag.Title = "Google Analytics";
}

<div class="content-header row">
    <div class="content-header-left col-md-6 col-12 mb-2">
        <div class="row breadcrumbs-top">
            <div class="breadcrumb-wrapper col-12">
                <ol class="breadcrumb">
                    <li class="breadcrumb-item">
                        <a href="@Url.Action("Index", "Home")">Home</a>
                    </li>
                    <li class="breadcrumb-item active">
                        Google Analytics
                    </li>
                </ol>
            </div>
        </div>
        <h3 class="content-header-title">Google Analytics</h3>

    </div>
    @*<div class="content-header-right col-md-6 col-12">
            <fieldset class="form-group relative has-icon-left col-md-5 col-12 float-right p-0">
                <input class="form-control" id="iconLeft" type="text" placeholder="Search...">
                <div class="form-control-position"><i class="fa fa-search"></i></div>
            </fieldset>
        </div>*@
</div>
<div class="content-body">
    <!-- Section start -->
    <section id="dom">
        <div class="row">
            <div class="col-12">
                <div class="card">
                    <div class="card-header">
                        <h4 class="card-title">Google Analytics</h4>
                        <a class="heading-elements-toggle"><i class="fa fa-ellipsis-v font-medium-3"></i></a>
                        <div class="heading-elements">
                            <ul class="list-inline mb-0">
                                <li><a data-action="collapse"><i class="ft-minus"></i></a></li>
                                @*<li><a data-action="reload"><i class="ft-rotate-cw"></i></a></li>*@
                                <li><a data-action="expand"><i class="ft-maximize"></i></a></li>
                                @*<li><a data-action="close"><i class="ft-x"></i></a></li>*@
                            </ul>
                        </div>
                    </div>
                    <div class="card-content collapse show">
                        <div class="card-body card-dashboard">
                            <form class="form form-horizontal">
                                <div class="form-body">
                                    <div class="row">
                                        <div class="col-12">
                                            <div class="card">
                                                <div class="card-header">
                                                    <div class="row">
                                                        <div class="col-4">
                                                            
                                                        </div>
                                                        <div class="col-4">
                                                            <div class="form-group mb-3">
                                                                <h5 class="text-center">Select Domain</h5>
                                                                @if (Model.lstDomains.Count > 0)
                                                                {
                                                                    @Html.DropDownListFor(Model => Model.iDomainID, new SelectList(Model.lstDomains, "iDomainID", "strTitle"), "-- Select A Domain --", new { @id = "lstDomains", @name = "lstDomains", @class = "select2 hide-search form-control block", @onchange = "jsGetDomainAnalytics()" })  <br />
                                                                    @Html.ValidationMessageFor(model => model.iDomainID, "", new { @class = "text-danger" })
                                                                }
                                                                else
                                                                {
                                                                    @Html.DropDownListFor(Model => Model.iDomainID, new SelectList(Model.lstDomains, "iDomainID", "strTitle"), "-- No Domains Available --", new { @id = "lstDomains", @name = "lstDomains", @class = "select2 hide-search form-control block" })
                                                                    <br />
                                                                    @Html.ValidationMessageFor(model => model.iDomainID, "", new { @class = "text-danger" })
                                                                }
                                                            </div>
                                                        </div>
                                                        <div class="col-4"></div>
                                                    </div>
                                                    <div>
                                                        <p id="pCardText" class="card-text">
                                                            Google Analytics Report
                                                        </p>
                                                    </div>
                                                </div>

                                                <div class="card-content collapse show">
                                                    <div class="card-body">

                                                        <div id='divGoogleAnalytics'></div>
                                                    </div>
                                                </div>
                                            </div>
                                        </div>
                                    </div>
                                </div>
                                <div class="form-actions right">
                                    <a href="@Url.Action("Index", "Home")" type="button" class="btn btn-warning mr-1">
                                        <i class="icon-arrow-circle-left"></i> Back
                                    </a>
                                    @*<a href="@Url.Action("BlogPostAdd", "BlogPosts")" type="button" class="btn btn-primary">
                                        <i class="icon-plus"></i> Add
                                    </a>*@
                                </div>
                            </form>
                        </div>

                    </div>
                </div>
            </div>
        </div>
    </section>
</div>

@section scripts {
<script type="text/javascript">

    function jsGetDomainAnalytics() {
        var iDomainID = $("#iDomainID").val();

        alert(iDomainID);

        $.ajax({
            url: '@Url.Action("GetDomainAnalytics", "Analytics")',
            type: "POST",
            data: { "iDomainID": iDomainID },
            success: function (data) {
                alert("GDA");
            }
        });
    }
</script>

<!-- Google Analytics -->
<script>
    function jsLoadGoogleAnalytics(propertyID) {
        (function (i, s, o, g, r, a, m) {
            i['GoogleAnalyticsObject'] = r; i[r] = i[r] || function () {
                (i[r].q = i[r].q || []).push(arguments)
            }, i[r].l = 1 * new Date(); a = s.createElement(o),
            m = s.getElementsByTagName(o)[0]; a.async = 1; a.src = g; m.parentNode.insertBefore(a, m)
        })(window, document, 'script', 'https://www.google-analytics.com/analytics.js', 'ga');

        ga('create', 'UA-XXXXX-Y', 'auto');
        ga('send', 'pageview');
    }
</script>
<!-- End Google Analytics -->
}

Views/Analytics/_DomainGoogleAnalyticsReportPartial.cshtml
@{
    Layout = null;
}

<div class="row">
    <!-- Simple Doughnut Chart -->
    <div class="col-md-8 col-sm-12">
        <div class="card">
            <div class="card-header">
                <h4 class="card-title">This Week vs. Last Week (By Sessions)</h4>
                <a class="heading-elements-toggle"><i class="icon-ellipsis font-medium-3"></i></a>
                <div class="heading-elements">
                    <ul class="list-inline mb-0">
                        <li><a data-action="collapse"><i class="icon-minus4"></i></a></li>
                        <li><a data-action="reload"><i class="icon-reload"></i></a></li>
                        <li><a data-action="expand"><i class="icon-expand2"></i></a></li>
                    </ul>
                </div>
            </div>
            <div class="card-body">
                <div class="card-block chartjs">
                    <canvas id="line-logarithmic" height="500"></canvas>
                </div>
            </div>
        </div>
    </div>
    <div class="col-md-4 col-sm-12">
        <div class="card">
            <div class="card-header">
                <h4 class="card-title">Where are your users?</h4>
                <a class="heading-elements-toggle"><i class="icon-ellipsis font-medium-3"></i></a>
                <div class="heading-elements">
                    <ul class="list-inline mb-0">
                        <li><a data-action="collapse"><i class="icon-minus4"></i></a></li>
                        <li><a data-action="reload"><i class="icon-reload"></i></a></li>
                        <li><a data-action="expand"><i class="icon-expand2"></i></a></li>
                    </ul>
                </div>
            </div>
            <div class="card-body">
                <div class="card-block">
                    <canvas id="analytics-doughnut-chart" height="400"></canvas>

                </div>
            </div>
        </div>
    </div>
</div>
<div class="row">
    <div class="col-md-4 col-sm-12">
        <div class="card">
            <div class="card-header">
                <h4 class="card-title">What are your top devices? </h4>
                <a class="heading-elements-toggle"><i class="icon-ellipsis font-medium-3"></i></a>
                <div class="heading-elements">
                    <ul class="list-inline mb-0">
                        <li><a data-action="collapse"><i class="icon-minus4"></i></a></li>
                        <li><a data-action="reload"><i class="icon-reload"></i></a></li>
                        <li><a data-action="expand"><i class="icon-expand2"></i></a></li>
                    </ul>
                </div>
            </div>
            <div class="card-body">
                <div class="card-block">
                    <canvas id="simple-pie-chart" height="300"></canvas>
                    <div class="row">
                        @*<div class="col-md-4 col-sm-4 col-4">
                                <div class="container" style="text-align:center">
                                    <i class="fas fa-desktop" style="font-size: 2.28rem;"></i><br />
                                    <label class="fonticon-classname">Desktop</label><br />
                                    <label id="desktop" class="fonticon-unit"></label>
                                </div>
                            </div>
                            <div class="col-md-4 col-sm-4 col-4">
                                <div class="container" style="text-align:center">
                                    <i class="fas fa-mobile-alt" style="font-size: 2.28rem;"></i><br />
                                    <label class="fonticon-classname">Mobile</label><br />
                                    <label id="mobile" class="fonticon-unit"></label>
                                </div>
                            </div>
                            <div class="col-md-4 col-sm-4 col-4">
                                <div class="container" style="text-align:center">
                                    <i class="fas fa-tablet-alt" style="font-size: 2.28rem;"></i><br />
                                    <label class="fonticon-classname">Tablet</label><br />
                                    <label id="tablet" class="fonticon-unit"></label>
                                </div>
                            </div>*@
                    </div>
                </div>
            </div>
        </div>
    </div>
    <div class="col-md-8 col-sm-12">
        <div class="card">
            <div class="card-header">
                <h4 class="card-title">What pages do your users visit? </h4>
                <a class="heading-elements-toggle"><i class="icon-ellipsis font-medium-3"></i></a>
                <div class="heading-elements">
                    <ul class="list-inline mb-0">
                        <li><a data-action="collapse"><i class="icon-minus4"></i></a></li>
                        <li><a data-action="reload"><i class="icon-reload"></i></a></li>
                        <li><a data-action="expand"><i class="icon-expand2"></i></a></li>
                    </ul>
                </div>
            </div>
            <div class="card-body">
                <div class="card-block">
                    <div id="main-chart-container"></div>
                </div>
            </div>
        </div>
    </div>
</div>